apiVersion: shipwright.io/v1alpha1
kind: ClusterBuildStrategy
metadata:
  name: ansible-builder
spec:
  buildSteps:
    - args:
        - -c
        - |
          set -e

          # rootless container support (Disabled until anyuid can be removed)
          #echo "ansible-builder:x:$(id -u):0:ansible-builder user:${HOME}:/sbin/nologin" >> /etc/passwd
          #echo $(id -u):1100000000:65536 >> /etc/subuid
          #echo $(id -u):1100000000:65536 >> /etc/subgid

          # Change into directory containing EE
          cd $(params.shp-source-context)

          # Create Ansible Build Context
          /usr/bin/ansible-builder create -c $HOME/context

          # Build the EE
          /usr/bin/buildah --storage-driver=vfs build -t $(params.shp-output-image) $HOME/context
      command:
        - /bin/bash
      image: "quay.io/ablock/ansible-builder-nested:latest"
      name: ansible-builder-build
      resources:
        limits:
          cpu: 1
          memory: 1Gi
        requests:
          cpu: 500m
          memory: 512Mi
      volumeMounts:
        - mountPath: /home/builder/.local/share/containers/storage
          name: ansible-builder-images
    - args:
        - --storage-driver=vfs
        - push
        - --digestfile=$(results.shp-image-digest.path)
        - "--tls-verify=false"
        - $(params.shp-output-image)
      command:
        - /usr/bin/buildah
      image: "quay.io/ablock/ansible-builder-nested:latest"
      name: ansible-builder-push
      resources:
        limits:
          cpu: 500m
          memory: 1Gi
        requests:
          cpu: 250m
          memory: 256Mi
      volumeMounts:
        - mountPath: /home/builder/.local/share/containers/storage
          name: ansible-builder-images
  volumes:
    - name: ansible-builder-images
      emptyDir: {}